# Generated by Django 3.2.7 on 2023-10-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demoUrl', models.URLField()),
                ('github', models.URLField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('gif', models.URLField()),
                ('description', models.TextField()),
                ('icons', models.CharField(max_length=200)),
                ('cardLang', models.CharField(max_length=200)),
                ('isDesign', models.BooleanField(default=False)),
            ],
        ),
    ]
